### ISSUE TITLE
Move to ELC repository?

### ISSUE THREAD

**Issue by IceAgeEcologist** [NeotomaDB/DwC-Mapping#4]
Hi Simon - I noticed that this RMD is in the NeotomaDB repo - should we move it to the EarthLifeConsortium repo?

Jack

**Comment by SimonGoring** [comment]
I think the plan is that this is the Neotoma specific document and will live here.  The related [elc repository](https://github.com/earthlifeconsortium/DwC-Mapping) is for the composite discussion, outlining the cross-walk, where the cross-walks differ &cetera.
